### ISSUE TITLE
new PowerPC instructions for accelerating wasm load/store

### ISSUE THREAD

**Issue by programmerjake** [WebAssembly/memory64#15]
I'm working on an initial draft design for some new PowerPC instructions that handles wasm memory32/64 load/store with hardware-level address range checking and base address addition:
https://bugs.libre-soc.org/show_bug.cgi?id=585

comments/questions/contributions welcome!

**Comment by aardappel** [comment]
Very cool!
See here for the bounds-checking semantics we ended up deciding on: https://github.com/WebAssembly/memory64/issues/3
You'll want to make sure your instructions match that behavior.

**Comment by sbc100** [comment]
Closing for now since memory64 is basically done now.   Hopefully these new instructions can be used to accelerate bounds check if/when they become available.
