### ISSUE TITLE
Modified spec link is dead

### ISSUE THREAD

**Issue by psoni2628** [WebAssembly/memory64#19]
The link to the modified spec in the README.md for this proposal is dead: https://webassembly.github.io/memory64. It would greatly appreciated if the correct link could be provided here.

**Comment by aardappel** [comment]
There is no modified spec yet.

There is only the overview (which has the intended spec changes): https://github.com/WebAssembly/memory64/blob/master/proposals/memory64/Overview.md

There is also the modified spec interpreter (https://github.com/WebAssembly/memory64/tree/master/interpreter) and tests (https://github.com/WebAssembly/memory64/tree/master/test/core, `*64.wast`) that all work.

If anything, that link could be removed for the moment.

**Comment by psoni2628** [comment]
I see. Thank you for the information!
