### ISSUE TITLE
64-bit shared memories specified with 32-bit limits

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/memory64#21]
I was reading over the [spec](https://github.com/WebAssembly/memory64/blob/master/proposals/memory64/Overview.md) again today and noticed that the binary encoding for limits for memories is specified as:

```
limits ::= 0x00 n:u32        ⇒ i32, {min n, max ϵ}, 0
        |  0x01 n:u32 m:u32  ⇒ i32, {min n, max m}, 0
        |  0x02 n:u32        ⇒ i32, {min n, max ϵ}, 1  ;; from threads proposal
        |  0x03 n:u32 m:u32  ⇒ i32, {min n, max m}, 1  ;; from threads proposal
        |  0x04 n:u64        ⇒ i64, {min n, max ϵ}, 0
        |  0x05 n:u64 m:u64  ⇒ i64, {min n, max m}, 0
        |  0x06 n:u32        ⇒ i64, {min n, max ϵ}, 1  ;; from threads proposal
        |  0x07 n:u32 m:u32  ⇒ i64, {min n, max m}, 1  ;; from threads proposal
```

It seems like the interpretation seems to be for the leading flags byte:

* 1st bit - whether or not a maximum is present
* 2nd bit - whether or not memories are shared
* 3rd bit - whether or not the memory is a 64-bit memory

This doesn't quite align with the table, though, specifically the last two cases:

```
        |  0x06 n:u32        ⇒ i64, {min n, max ϵ}, 1  ;; from threads proposal
        |  0x07 n:u32 m:u32  ⇒ i64, {min n, max m}, 1  ;; from threads proposal
```

these are currently specified as a 32-bit specification of the min/max sizes instead of what I was naively expecting as a 64-bit specification.

Is this intentional? (or perhaps a typo?) If this is intentional, could a few words be added as to why shared memories don't get 64-bit limits just yet (I'm not sure myself, mostly just curious!)

**Comment by aardappel** [comment]
Pretty sure that's a typo, limits are 64-bit independently of the other 2 flags, and that's how it is implemented so far in the tools.

Care to make a PR?

@rossberg

**Comment by alexcrichton** [comment]
Ok makes sense and that's what I figured, just wanted to confirm! I'll send a PR to update the overview tomorrow

**Comment by rossberg** [comment]
Yes, that looks like a C&P error.

**Comment by davnavr** [comment]
I was fuzzing a WASM parser I made, and found that the current [overview still has the typo](https://github.com/WebAssembly/memory64/blob/d456ed8ab94ac06ff30cd2c8aaaed6671b4a13f6/proposals/memory64/Overview.md#binary-format). Maybe someone can merge the changes into `main`?

**Comment by sbc100** [comment]
That is strange.  I have no clue why that PR was closed rather than merged..
