### ISSUE TITLE
JS API changes?

### ISSUE THREAD

**Issue by lars-t-hansen** [WebAssembly/memory64#24]
This proposal looks like it might need changes to the JS API, off the top of my head at least these:

- the index type needs to be described in the memory descriptor (our prototype uses the key "index" for this)
- the current JS API enforces the range of initial and max to be unsigned long, ie, a u32, but this proposal requires something better than that

**Comment by aardappel** [comment]
Not familiar with the JS API design myself.. @backes did you run into this?

**Comment by backes** [comment]
I didn't hit this yet, but the V8 implementation is not complete yet. Also, we currently still only allow up to 4GB memories, even if you use 64 bit for indexing.

But I agree that the JS API will need changes.

**Comment by sbc100** [comment]
@lars-t-hansen what do you propose for the value of "index"?   The string `u64` or `u32` maybe?

**Comment by eqrion** [comment]
SpiderMonkey currently uses “i32” and “i64” for the JS-type representation of index type. IIRC, that’s what the memory64 proposal uses in the text format, so we were trying to stay symmetrical to that.

**Comment by sbc100** [comment]
I believe this is fixed by #39
