### ISSUE TITLE
Text format: new abbreviation for inline data?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/memory64#29]
The current spec gives this abbreviation for specifying data inline in a memory definition:

```
'(' 'memory' id? '(' 'data' b*:datastring ')' ')'
```

The memory limits are inferred from the size of the data string. For back compat, this abbreviation needs to continue specifying a 32-bit memory, but should we add a similar abbreviation for 64-bit memories? As an example:

```
'(' 'memory' id? '(' 'data' 'i64' b*:datastring ')' ')'
```

We could also choose not to provide such an abbreviation.

**Comment by rossberg** [comment]
Yes, makes a lot of sense to me. However, I think the syntax ought to be
```
'(' 'memory' id? idxtype '(' 'data' datastring ')' ')'
```
Reason: The index type is part of the memory type, not the data. Inline data (or inline elem) only modifies the preceding syntax of memory (or table) definitions in so far that their limits are omitted.

**Comment by tlively** [comment]
I agree that syntax would make more sense, but it would mean that a parser that doesn't expand abbreviations wouldn't know from looking at the idxtype token whether to parse a memtype or an idxtype followed by data. That's not a huge problem, but it is a little annoying.

**Comment by rossberg** [comment]
@tlively, I guess I'm willing to live with that small annoyance. :) The analogous shorthand for tables already works that way, although the order is different there, so the annoyance doesn't come up, I suppose.

**Comment by bvisness** [comment]
The current version of the spec already supports the syntax from [this comment](https://github.com/WebAssembly/memory64/issues/29#issuecomment-1284980306), and at least wasm-tools has implemented it. Also, I recall from a discussion with @tlively in Pittsburgh that naive expansion of abbreviations in the text format was already not viable because of existing things in the spec.

Is there anything else to do on this issue or could it be closed?

**Comment by tlively** [comment]
I'm happy to close it without adding an abbreviation if everyone else is happy to close it. @sbc100?

**Comment by sbc100** [comment]
Yes, I believe the syntax from https://github.com/WebAssembly/memory64/issues/29#issuecomment-1284980306 is already supported and tested in test/core/float_memory64.wast and test/core/memory64.wast.
