### ISSUE TITLE
`call_indirect` reserved byte in binary tests

### ISSUE THREAD

**Issue by adambratschikaye** [WebAssembly/memory64#32]
It looks like some of the tests in `binary.wast` are checking that the table index to `call_indirect` instructions is `0x00`: https://github.com/WebAssembly/memory64/blob/d0fbbe7b1d3c2cabf8409a48f70c94956ebfbe7f/test/core/binary.wast#L69 But that doesn't seem to be required in the [spec](https://webassembly.github.io/spec/core/binary/instructions.html#control-instructions). Is that just left over from an older version?

**Comment by titzer** [comment]
Indeed, that seems to be leftover from days before `bulk-memory` landed.

**Comment by sbc100** [comment]
I think this can be closed now since this proposal now up-to-date with the upstream spec and now includes 7fa2f20a6df4cf1c114582c8cb60f5bfcdbf1be1 which removed the line in question.

**Comment by adambratschikaye** [comment]
Thanks @sbc100
