### ISSUE TITLE
Modified spec link is dead

### ISSUE THREAD

**Issue by RReverser** [WebAssembly/memory64#35]
> See the [modified spec](https://webassembly.github.io/memory64/) for details.

This link in README seems dead.

**Comment by sbc100** [comment]
Ah, I guess that auto-public action was never setup/run.   I can fix that I think.

(BTW, do most proposal publish their modified spec?)

**Comment by dschuff** [comment]
Some of them do. There's https://webassembly.github.io/exception-handling/ and https://webassembly.github.io/threads/ but no https://webassembly.github.io/gc or https://webassembly.github.io/javascript-promise-integration. I guess it makes sense once you get into phase 3 and are updating the spec document.
