### ISSUE TITLE
Change memory.size/grow to use index type

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/memory64#69]
Related to #68, the operand/result types of the memory.size and memory.grow instructions need to use the index type of the respective memory as well. Otherwise the Memory64 proposal will be incompatible with the custom page size proposal, which allows page sizes of 1.

**Comment by sbc100** [comment]
IIUC this is already the case.  See https://github.com/WebAssembly/memory64/blob/aae6d053cd50f4108245f2225181c05e9040a943/proposals/memory64/Overview.md?plain=1#L129-L139

**Comment by rossberg** [comment]
Ah yes, sorry for the noise, I somehow managed to look in the wrong place.
